# Conclusion

 - This work presents the analysis of D1NAMO dataset. The dataset focuses on monitoring health, activity and food intake measurements under everyday-life conditions in patients with and without diabetes type-1.

 - Acquisition of data took place in everyday-life conditions with chest belt. Hence, the dataset has noisy parts as well as missing data. This makes the dataset ideal for the development and evaluation of algorithms for wearable healthcare systems.
 - Analyzed glucose together with food information permitting to explore the impact of calories, food balance or food quality on the glucose levels.

## Limitations

 - Data is inconsistent regarding annotated food items. Information regarding the timestamp of food intake for diabetic patients are missing. The following data can help analyze the impact of diet on glucose level. It can also be used in recommending the insulin dose and diet to avoid hypoglycemic events.

## Future Work

 - We analyzed the relationship between hypoglycemic events and shape of ECG beats. It can be extended to find relationship between food intake, activity levels, as well as heartbeat and breathing monitoring. This can substantially show trends in early detection of hypoglycemic situations.
 - Processing and visualisation of noisy signals to discard parts that are not usable and to keep only the clean/usable portions can be performed. Such works can also be applied on this dataset, e.g. focusing only on time windows relevant to an activity, or a portion of the data where noise does not increase over a certain threshold.




