--- 
title: "Data analysis of type 1 diabetes management"
author: "Shivani Modi and Sriram Dommeti"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

We are interested in exploratory data analysis of a health care data set.

We came across recent research on non-invasive type 1 diabetes management. D1NAMO (https://zenodo.org/record/1421616#.X3G7wpMzadY) dataset has been approved by the scientific community to allow for the research and analysis of diabetes management.

They acquired 20 healthy subjects and 9 patients with type-1 diabetes. The acquisition has been made in real-life conditions with the Zephyr BioHarness 3 wearable device. The dataset consists of ECG, breathing, and accelerometer signals, as well as glucose measurements and annotated food pictures.

8414 measurements of glycemic levels have been made for people with Type 1 Diabetes for more than 1500 hours. Huge dataset!

After going through the paper (https://doi.org/10.1016/j.imu.2018.09.003) to understand this dataset, we listed down some of the insights which can be extracted from the dataset either through visualization or summary statistics:

*	What is the difference in the glucose levels just before eating and 2 hours after eating? Extracting insights and comparing trends between healthy and diabetic patients.
*	Explore correlations between changes in glucose level in the blood and ECG signals.
*	Analyze the possibilities of activity levels and food intake having an influence on glycemic events.
*	This dataset having subsets of healthy people and patients with diabetes, at a broader level we are interested to compare and explore the impact of Type 1 diabetes with the reference group i.e, characteristics of various measurements between the groups.
*	Explore the impact of calories, food balance or food quality on the glucose levels. Analysis will be done using annotated food information.